CREATE TABLE IF NOT EXISTS hosts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    user TEXT NOT NULL,
    so TEXT NOT NULL,
    address TEXT NOT NULL,
    password TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS user_login (
    user TEXT NOT NULL,
    password TEXT NOT NULL
)

CREATE TABLE IF NOT EXISTS user_logs (
    name TEXT NOT NULL,
    time NUMERIC NOT NULL DEFAULT CURRENT_TIMESTAMP
)
